"""Persistence contracts used by the workflow."""

from typing import Any, Protocol


class StateStore(Protocol):
    def save_state(self, state: dict[str, Any], status: str = "running") -> None: ...
    def record_node(self, task_id: str, node: str, status: str, detail: str = "") -> None: ...
    def record_error(self, task_id: str, node: str, message: str) -> None: ...
    def load_state(self, task_id: str) -> dict[str, Any] | None: ...
    def task_status(self, task_id: str) -> str | None: ...
    def latest_node_run(self, task_id: str) -> dict[str, Any] | None: ...
